# Generated by Django 3.0.5 on 2020-12-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('ticker', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
