# Generated by Django 3.0.5 on 2021-01-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='emisor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
